services:
  doc-elastic:
    image: elasticsearch:8.5.3
    restart: unless-stopped
    volumes:
      - doc-elastic-data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      discovery.type: "single-node"

  doc-kibana:
    image: kibana:8.5.3
    restart: unless-stopped
    ports:
      - "127.0.0.1:5601:5601"

  # logstash, beats?


  doc-db:
    image: mongo
    restart: unless-stopped
    volumes:
      - doc-db-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  doc-db-admin:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@doc-db:27017/

volumes:
  doc-db-data:
  doc-elastic-data:
