server:
  port: 8888
  error:
    include-stacktrace: never

logging:
  level:
    org.whatsthelaw.whatsthelaw: "debug"

spring:
  data:
    mongodb:
      uri: "mongodb://root:root@localhost:27017/doc?authSource=admin"

app:
  congress-api:
    root-uri: ${CONGRESS_API_ROOT_URI}
    key: ${CONGRESS_API_KEY}
